export type TourbillRecord = {
  id: number;
  tourid:number;
  userid: string;
  created_on: string;
  da_calculated:number;
  ta_claimed:number;
  other_expenses:number;
  other_expense_remarks:string;
  total_claim:number;
  work_order:string;
  mgr_action_by:string;
  mgr_action_date:Date;
  mgr_remarks:string;
  mgr_approved_amt:number;
  finance_action_by:string;
  finance_action_date:Date;
  fin_remarks:string;
  finance_approved_amount:number;
  ticket_status:string;
};